### ISSUE TITLE
Default Soundfont is not configured

### ISSUE THREAD

**Issue by jostle** [lenmus/lenmus#100]
I have just built from a fresh `git clone`.
Cmake reported finding the soundfont as 

    Checking for LenMus dependencies:
    -- FluidR3_GM.sf2 found in /usr/share/sounds/sf2

but when I run the program I get the following

    fluidsynth: error: Unable to open file "/usr/share/sounds/FluidR3_GM.sf2"
    fluidsynth: error: Couldn't load soundfont file
    fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/FluidR3_GM.sf2"
    fluidsynth: warning: Failed to load SoundFont "/usr/share/sounds/FluidR3_GM.sf2"

It is easy to fix by going to `Preferences -> Sound` and changing the setting but, I think, it would be better to fix the default as part of the build process.

**Comment by cecilios** [comment]
Thanks for reporting.

The default location is passed to the program in the build process. Probably the problem is that you already had another previous installation of LenMus and, as  the configuration file is not deleted when a new installation is done, LenMus used the path in that configuration file instead of the default location.

I'm currently looking into another issue. I will look at this one as soon as posible.

**Comment by cecilios** [comment]
For which platform are you building?

**Comment by jostle** [comment]
Sorry, should have said, building on Ubuntu 19.10 
I had not previously installed LenMus, just cloned the project and followed the build instructions.

**Comment by cecilios** [comment]
Ok, thanks
