### ISSUE TITLE
Wrong dependency on libwxgtk3.0-0v5 for Ubuntu 20.4 (should be libwxgtk3.0-gtk3-dev instead?)

### ISSUE THREAD

**Issue by jmygt** [lenmus/lenmus#110]
Hi.

As of today, Lenmus cannot be installed from Ubuntu Focal (20.04) repositories due to an unmet dependency
```
lenmus : Depende: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) pero no es instalable
```
It seems that the dependency should be on libwxgtk3.0-gtk3-dev instead. See [this](https://packages.ubuntu.com/search?keywords=libwxgtk) (you will not see libwxgtk3.0-dev for Focal, but libwxgtk3.0-gtk3-dev) and e.g. [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943439).

The [instructions to build lenmus in Linux](http://lenmus.org/es/phonascus/building-linux) do not work either because of the same problem. Installing the `libwxgtk3.0-gtk3-dev` from the sources (instead of  libwxgtk3.0-dev as per the building instructions) solved this issue, in that the compilation was successful. The instructions should then be updated for Focal, and perhaps other distros.

Cheers!

**Comment by cecilios** [comment]
Thank you!

> It seems that the dependency should be on libwxgtk3.0-gtk3-dev instead. 

Yes, I found that after devoting two days to investigate why I was able to build 5.6.0 in Focal (see the build log for 5.6.0 still in the PPA) but a few days later it didn't built. For me the problem is that all Ubuntu packages are built automatically from Debian files. And Debian file specifies a dependency from libwxgtk3.0-dev (>= 3.0). This worked OK until now, when someone decided to rename, in Focal, libwxgtk3.0 as libwxgtk3.0-gtk3.

I don't know how to solve this, as I'm not knowledgeable neither in Debian packaging not in Launchpad system for building packages. Perhaps it is possible to define alternatives in the Debian control file.

So, when the problem arose, I was tired of having to learn how to build installation packages for each Linux flavor, so I decided to leave the task of building packages to each distro packagers or to lenmus collaborators and just build AppImage packages and, perhaps, in future, Flatpack and Snap packages. As long as Launchpad is able to build packages for Ubuntu I will try to maintain the PPA, but I would like to devote my time to project management, design and development and not to learning the nuisances of building packages for each Linux distro.

I will add a notice in the build instructions for Focal. I don't know about other distros.

Thanks again for reporting.
