### ISSUE TITLE
Why does Windows defender say contains ransomware

### ISSUE THREAD

**Issue by aubreyz** [lenmus/lenmus#111]
At least it does for the sourceforge version here https://sourceforge.net/projects/lenmus/

that links to this page.....

**Comment by aubreyz** [comment]
Windows version downloaded http://www.lenmus.org/en/phonascus/download-windows

is also reported as containing ransomware

**Comment by cecilios** [comment]
Both links points to the official download at SourceForge, so it should be a clean official version. I have downloaded the file and verified the SHA256 checksum (it is displayed in  http://www.lenmus.org/en/phonascus/download-windows) so the file has not been modified and thus it is the original safe file. 

I don't know why Windows defender syas it contains ransomware but it is a false positive. Anyway, this is a problem for LenMus users and thus for me. Could you please send me screenshots or other information so that I can investigate more and try to fix this?

**Comment by cecilios** [comment]
Scanning with a good online scanners, such as https://virusscan.jotti.org/, that uses most of the commercial malware scanners does not report any problem.
![virus-scan](https://user-images.githubusercontent.com/5238679/83348867-80a0c900-a330-11ea-870b-0347ec4aa5d9.png)

**Comment by aubreyz** [comment]
I tried again today and the ransomware alert message from Microsoft did not come up again. I suspect it was a temporary bit of heuristic detection that MS might have removed in the interim. I have seen this kind of thing before from these black box detectors. I have not yet tried the software so can't yet thank you for writing it. But thank you.

**Comment by cecilios** [comment]
Ok. Glad to know. Thank you!

**Comment by regis586** [comment]
06/07/2020
Hi,
same thing with Lenmus 5.6.0 and Windows Defender
![20200706-Defender-Alerte Ransomware-Lenmus-2](https://user-images.githubusercontent.com/67907497/86593361-59739200-bf95-11ea-9e57-86914e679bd9.jpg)
