### ISSUE TITLE
Some missing items when running on Fedora 33 (Wayland)

### ISSUE THREAD

**Issue by ig-perez** [lenmus/lenmus#130]
Hi, thanks a lot for creating and maintaining this excellent application. I just downloaded the Appimage and when executing I get next errors:
1. `Gtk-Message: 19:08:33.798: Failed to load module "canberra-gtk-module"`
2. `Gtk-Message: 19:08:33.799: Failed to load module "pk-gtk-module"`

There are also several warnings, among them, the most common is:
```
Error loading theme icon 'window-close' for stock: Unable to load image-loading module: /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib64/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations
```
I tried to install the missing modules, but there are several options and I don't know which one to pick:
```
libcanberra-devel.i686 : Development Files for libcanberra Client Development
libcanberra-devel.x86_64 : Development Files for libcanberra Client Development
libcanberra-gtk2.x86_64 : Gtk+ 2.x Bindings for libcanberra
libcanberra-gtk2.i686 : Gtk+ 2.x Bindings for libcanberra
libcanberra-gtk3.x86_64 : Gtk+ 3.x Bindings for libcanberra
libcanberra-gtk3.i686 : Gtk+ 3.x Bindings for libcanberra
python3-canberra.noarch : A very basic (and incomplete) wrapper for libcanberra
=============== Name Matched: canberra ===================
libcanberra.x86_64 : Portable Sound Event Library
libcanberra.i686 : Portable Sound Event Library
```
On regards the `pk-gtk-module` one, no clue, couldn't find anything for that within Fedora Fusion or default repos.

Thanks!

**Comment by cecilios** [comment]
Thanks for reporting.

From your post, it is not clear to me if lenmus is running or the Gtk error messages prevent it to run.

Sometimes, when running lenmus from a terminal window (as well as other applications), I have observed some warning messages related to Gtk, but these messages are informative and never caused any problem, and lenmus run perfectly. I never investigated these messages as I'm not using Gtk directly so I do not know how to debug this. 

In any case, I have no idea about how to fix this. Looking at the list of gtk libraries included in the AppPackage, it uses libgtk-x11-2.0. Perhaps some modules expected by this library are not present in Fedora 33 because it uses a libgtk-x11 version greater than 2.0. But no idea.

The best solution would be to build from sources. It is very simple (instructions [here](https://github.com/lenmus/lenmus/blob/master/docs/building/linux-build-instructions.md) ). In step 2, do not use the latest sources in master branch but the sources included in the latest release (5.6.2).

**Comment by ig-perez** [comment]
Hola Cecilio, sorry for not being clear enough. Lenmus is indeed running with those errors and warnings shown in the terminal window.

I'm just starting to use Lenmus so I can't tell yet if it is working as expected, one small thing I see is that the `x` icon to close the tabs is not loaded. 

I'm going to follow your advice and build it from source and will report with the results as soon as I can.

Saludos
Iván

**Comment by ig-perez** [comment]
I just did it and the build process run without an issue, sadly the scrollbars are not working and I can't click on the play buttons of the lessons. I guess that might be related with Fedora is running with Wayland instead of X11. But that worked with the AppImage, odd.

Any advice?

**Comment by cecilios** [comment]
Thanks for the info.

Really I can not be of help in this issue. Lenmus is built using the wxWidgets framework and wxWidgets uses different OS specific libraries to use native controls. The version I have installed in my machine uses Gtk, and it uses X11. I don't know what is the situation width Wayland and wxWidgets. This post  [https://forums.wxwidgets.org/viewtopic.php?t=43022#p174851](https://forums.wxwidgets.org/viewtopic.php?t=43022#p174851) suggests that in 2017 there were still issues to run wxWidgets application with Wayland.

On the other hand, Wayland project has developed gtk libraries to work with Wayland instead of X11. So my gess is that the gtk libraries installed in Fedora 33 with Wayland are the ones patched by Wayland developers.

When using the AppImage, I understand that it contains the app and all its dependencies, so when you run the LenMus AppImage it is using the X11 libraries included in the AppImage. But when building lenmus and running it, it will use the Gtk libraries in your system and, I guess, these are the Gtk libraries patched by Wayland developers. This would explain the different behaviour.

As to how to debug the issues you have detected, I would start by building the wxWidgets sample for scrollbars and check if it works. If the scroll bars issue is not present in that sample, the bug will be probably in lenmus code. Otherwise, if the bad behaviour in scrollbars is also in the sample, the bug is probably in the gtk-wayland libraries.

Un cordial saludo

**Comment by ig-perez** [comment]
Thanks Cecilio. I'd like to troubleshoot following your guidelines sadly I don't have spare time for this. I'm closing the issue for the time being
