### ISSUE TITLE
Genasom ransomware 

### ISSUE THREAD

**Issue by robduncan1** [lenmus/lenmus#142]
Hi, 
MS Defender detects Genasom ransomware when this app is downloaded from source forge
http://sourceforge.net/projects/lenmus/files/For%20Windows/lenmus-5.6.0-x64-setup.exe/download

Please do not download this as you will become infected

**Comment by cecilios** [comment]
Thanks for informing. Have you checked the SHA256 Checksum of the downloaded file for detecting if it has been altered?:
53cf9a2bceed45424ca9171dd1f66c2b405200a0ab859304fe7f787705f34520

**Comment by cecilios** [comment]
I've downloaded the file and checked the checksum. The file is correct. It has no been altered. It looks as a false positive. (See issues #123 and #111)

Anyway, try checking the binaries with an online antivirus service that uses several antivirus, such as Virus Total (https://www.virustotal.com) or the Jotti malware scanner (https: //virusscan.jotti. org) that quickly check a file against more than 50 virus and malware detectors.

This false positive seems to be caused because both the installer and the uninstaller are created with NSIS software. It is due to the way NSIS works, that Microsoft does't like: http://stackoverflow.com/questions/48833995/ddg#48835095

It would be nice if someone could create and maintain a new installer for Windows, using modern tools. I no longer work with Windows so can not do this.

**Comment by robduncan1** [comment]
Thanks Cecilio,

yes, I have checked the hash and it matches, also my Cylance AV scanner did not pick anything up - I checked out the other issues and stack overflow answer and it does seem to be a false positive. This is unfortunate as it will possibly effect adoption with Windows users. If I could help, I surely would but I do not have the requisite experience, perhaps the issue is because there is no uninstall option and lenmus is not listed in the add/remove programs utility ? - thanks for your help
________________________________

**Comment by cecilios** [comment]
> This is unfortunate as it will possibly effect adoption with Windows users

Yes, for sure. But open software depends on collaborators and nobody helps in maintaining a Windows version. A pity.

Thank you very much for reporting.
