### ISSUE TITLE
Click on 'Study guide' lets application crash

### ISSUE THREAD

**Issue by BeFrankly** [lenmus/lenmus#144]
Hello developers, good job done so far. 
Here is a bug I found:

If in the main window fist clicking on 'Open the music books' a modal dialog window is shown. If one clicks 'Study guide' within that dialog the whole application crashes. This behavior is shown on a Ubuntu 20.04 system when using the Lenmus AppImage.

First I thought it happens because I'm using the german translation but when I choose English as a language behavior is the same.

Regards
Frank

**Comment by cecilios** [comment]
Thanks for reporting. I've checked this and I can confirm the bug.

But this problem is already fixed in the new version 6.0 that will be released in February, so I'm closing this issue as the repo is currently updated to the latest code.

In the new version the main window changes a little and the book selection dialog no longer exists. Now the books will be selected directly in the main window, as well as the study guide.

Thanks again for reporting bugs. Regards,
Cecilio
