### ISSUE TITLE
Feature: Keyboard control for comforable use of the exercises

### ISSUE THREAD

**Issue by BeFrankly** [lenmus/lenmus#145]
Hello,
some hours ago I found this project and think it has a lot of what I was looking for. But what I am missing is the possibility to control the exercises by Keyboard. 

It would be great if someone adds this feature. Take a look at GNU Solfege  i.e. This has a minimum of Keyboard controlling.

Regards

Frank

**Comment by cecilios** [comment]
Thanks for the suggestion. Conceptually the idea of ​​using the keyboard is very interesting, but it has difficulties that I don't know how to solve.

I don't know GNU Solfege but the idea of ​​controlling the exercises from the keyboard was discarded a long time ago, because it required solving many design problems and it didn't seem easy to find solutions. The first one is how to assign keys to answer buttons. It is very difficult to find mnemonic rules to help you remember which key corresponds to which button. In some exercises there are many answer buttons, for example in interval types, and it is not possible to use key combinations, just a single key per button.

On the other hand, even if some mnemonic algorithm is found to remember which key corresponds to which button, there is the problem of translations. For example, in an exercise where the answers are the note names it may seem obvious that the most suitable keys would be to use C D E F G A and B. But that is only valid for English speakers. For someone who speaks German it is probably easier and more mnemonic to use D R M F S L T. So the keys must be adaptable to each language.

Finally, it would be necessary to show the name of the associated key next to each response button and add documentation (which must be maintained and translated and that nobody reads) explaining the entire system. Too much work for me!

If you can think of ways to do this and solving these problems, please let me know. Thank you.

**Comment by cecilios** [comment]
I am closing this issue as there is no further feedback to clarify the needs.
