### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Musicpal** [lenmus/lenmus#150]
Thank you so much for this ear training program.
Just installed it today from a rpm package for SUSE Linux 15.3

But can't get it to go, the start page shows up but then after start it says 'file not found'

Thanks in advantage.

Peter

**Comment by cecilios** [comment]
> the start page shows up but then after start it says 'file not found'

Did you click on any link/button? or the message came out by itself?

**Comment by cecilios** [comment]
I'm assuming that you clicked on a link to open the exercises or a book. If that was the case, I've seen here (https://opensuse.pkgs.org/15.3/education-x86_64/lenmus-6.0.0-lp153.1.1.x86_64.rpm.html) and here (https://opensuse.pkgs.org/15.3/education-x86_64/lenmus-lang-6.0.0-lp153.1.1.noarch.rpm.html)  that the OpenSuse people have split the program into two packages, one with the program (lenmus-6.0.0-lp153.1.1.x86_64.rpm) and the other one with the books (lenmus-lang-6.0.0-lp153.1.1.noarch.rpm).

I think your problem is that you also have to install package lenmus-lang-6.0.0-lp153.1.1.noarch.rpm.

**Comment by cecilios** [comment]
I am closing this issue as there is no further feedback, so it appears to be resolved.  If you believe things are still unresolved please let me know and I can reopen if needed.
