### ISSUE TITLE
error: invalid new-expression when building with wxWidgets >= 3.1.6

### ISSUE THREAD

**Issue by kolewu** [lenmus/lenmus#151]
When building with wxWidgets >= 3.1.6 there is a build error
```
error: invalid new-expression of abstract class type 'lenmus::BookContentBox'
```
because of a changed signature of an overloaded pure virtual function. The fix is easy: [Fix SetHTMLBackgroundImage parameter](https://github.com/kolewu/lenmus/commit/4a4a1ac4d1eafa285ec3eecd55053dc1eaf7939c) but I'm not sure howto do this in the project context with different target versions of wxWidgets.

The change in wxWidgets, that triggers this error is here: [Use wxBitmapBundle in wxHtmlWindow ](https://github.com/wxWidgets/wxWidgets/commit/7a2a1e9074b70bfe1bb5527c2c54e3135b719959)

For Archlinux/Manjaro I have added a patch to the [build recipe](https://aur.archlinux.org/packages/lenmus)

**Comment by cecilios** [comment]
Thanks for reporting and for all the information, and sorry for the late reply, I've on holidays and returned yesterday night.

This issue seems to be easy to fix, as you did, but for supporting different wxWidgets versions I will have to include a conditional compilation macro to check for the version. The range of wxWidgets versions in Linux distros greatly vary from 2.8.12 to 3.2 (https://repology.org/project/wxwidgets/versions)
