### ISSUE TITLE
[Feature request]: Don't bundle fonts

### ISSUE THREAD

**Issue by lgbaldoni** [lenmus/lenmus#77]
Especially wqy-zenhei that's particularly builky, but also Liberation and Bravura.

I tried creating a patch for openSUSE but I wasn't sure about the best way to use system-installed fonts instead.

**Comment by cecilios** [comment]
I agree that bundling fonts must be avoided, as well as other resources. I have the idea of splitting the Linux package into four packages:

- **lenmus-main**. This package will provide just the executable.

- **lenmus-common**. This package will provide common support files not bound to any particular release, architecture or language, such as fonts, soundfonts, icons, samples and templates.

- **lenmus-lang**. This package will provide the i18n message catalogs for lenmus, so that program translations can be updated at any moment.

- **lenmus-ebooks**. This package will provide the eBooks (all translations). eBooks will be provided in a separate package so that books can be updated at any time.

But until this split can be finished, it is necessary to maintain an additional package:

- **lenmus**. It is the current package, containing everything. It will be a transitional package until the split is finished, to ensure that users can install lenmus without more problems.

These are my current plans. Unfortunately, there are several issues that forces me to postpone this:
- Modifying the CMakeList.txt with options for generating all these packages, and also the current package containing everything, is a lot of work for me, as I have very little knowledge about packaging.
- I work alone in this project (I always failed at creating a team of maintainers).
- The split into several packages does neither provide any gain to me or to LenMus users:
    - For the users more complication: need to install several packages instead of one.
    - For me it is just more work to do the split, and once done, more work to maintain it and more questions from users due to failures to install because the need to install several packages instead of one.

So I'm afraid solving this issue will be postponed until I get help to do it. A PR with the modifications to do to the CMakeList.txt, adding options for generating all these packages, and also the current package containing everything, will be specially welcome!

This issue is the same or very related to issues #42, #48 and #49.

**Comment by cecilios** [comment]
After some tests I have found the way to do this using CPack. Hope to have lenmus split in several packages in a few days!

**Comment by lgbaldoni** [comment]
Actually my question was another: will lenmus detect all fonts if installed in e.g. /usr/share/fonts/truetype without any source modification?

**Comment by cecilios** [comment]
> will lenmus detect all fonts if installed in e.g. /usr/share/fonts/truetype without any source modification?

No, source code modification is necessary and is platform dependent. It is not a requirement of LenMus but a requirement from lomse library. See:
https://github.com/lenmus/lomse/issues/102

I'm inclined to develop  platform dependent lomse modules for dealing with fonts. But to go on with this I need to have contributors with knowledge of the different platforms. I only can do it for Linux, and currently I would need also a solution for Windows. And in a few months also for Android  and for macOS, as these portings are going on.

**Comment by cecilios** [comment]
Fixing this, so that LenMus uses system-installed fonts, is important and would be well worth doing it, but requires more time than I can possibly spend on it now. But I've been looking into a simple solution for fixing this until a definite solution can be coded.

The solution will be only for Linux and will require some code modification (not much). Also, installation packages will have to set a dependency from some fonts:
- from "fonts-wqy-zenhei" and “fonts-liberation” packages.
- And from Bravura font. For OpenSUSE there is a package from steinberg
   https://opensuse.pkgs.org/tumbleweed/fonts-x86_64/steinberg-bravura-fonts-1.276-3.1.noarch.rpm.html
  But there are no packages for Debian based distros, so I will have to create a "font-bravura-lenmus" package.

I will have to modify cmake script to look for fonts in system font folders, and as they are different on each linux distro it will be of great help if you could give information about system font folders in OpenSUSE or any other distro you know well.

Do you think this solution could solve your problems?

**Comment by lgbaldoni** [comment]
I packaged the bravura font myself for that purpose.
On openSUSE there's the %{_ttfontsdir} rpm macro pointing at /usr/share/fonts/truetype, at least on Leap and Tumbleweed.

I can live with an additional patch for the font path, I just need to know where to hardcode it at buildtime if a cleaner solution is not possible at the present.

**Comment by lgbaldoni** [comment]
Excellent, will try building from master at once.

Just a doubt though, could this https://github.com/lenmus/lenmus/blob/7e1e7be8ccf8a0f2f00c1298ee1d3240534ac7b0/lomse/trunk/src/platform/lomse_linux.cpp#L173  be a typo?

**Comment by cecilios** [comment]
Thanks. It is not a typo. I preferred to omit the "B" just in case a distro use only lower cases letters for the font filename. Transforming the path to capital letters for comparison is unnecessary work.
